name: moveit2-base-jazzy
title: MoveIt2 snap for ctrlX
version: '2.1.2'

summary: Provides MoveIt2 and ros2_control functionalities for ctrlX CORE

description: |
  MoveIt2 overlay snap running on top of ros2-base-jazzy.

base: core24

grade: devel
confinement: strict

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  moveit-base:
    plugin: dump
    source: ./install
    stage-packages:
      # MoveIt2
      # - ros-jazzy-moveit
      - ros-jazzy-moveit-core
      - ros-jazzy-moveit-ros-planning
      - ros-jazzy-moveit-ros-move-group
      - ros-jazzy-moveit-planners-ompl
      - ros-jazzy-moveit-kinematics
      - ros-jazzy-moveit-simple-controller-manager
      # - ros-jazzy-moveit-ros-perception
      # - ros-jazzy-moveit-servo
      # - ros-jazzy-moveit-visual-tools

      # ros2_control
      - ros-jazzy-ros2-control
      - ros-jazzy-ros2-controllers
      - ros-jazzy-gripper-controllers

      # Utilities
      - ros-jazzy-xacro

      # DDS plugin
      - ros-jazzy-rmw-cyclonedds-cpp

  scripts:
    plugin: dump
    source: ./scripts
    organize:
      '*': usr/bin/

slots:
  moveit-base:
    interface: content
    content: moveit-runtime
    read:
      - /

plugs:
  ros-base:
    interface: content
    content: executables
    target: $SNAP/rosruntime
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer